# =========================================================================
#     This makefile was generated by
#     Bakefile 0.2.13 (http://www.bakefile.org)
#     Do not modify, all changes will be overwritten!
# =========================================================================


OPENCVLIB 		= `pkg-config opencv4 --cflags --libs`

INSTALL = /usr/bin/install -c
LIBS = -lz -ldl -lm
CXX = g++
TOOLKIT = GTK
EXTRALIBS = -pthread  -lz -ldl -lm
EXTRALIBS_XML =  -lexpat
EXTRALIBS_GUI = -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lgthread-2.0 -pthread -lglib-2.0 -lX11 -lXxf86vm -lSM -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lXtst -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lharfbuzz -lfontconfig -lfreetype -lpng -lz -ljpeg -ltiff -ljbig
WX_CPPFLAGS = -Ilib -Ilib/include -D_FILE_OFFSET_BITS=64 -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include 
WX_CXXFLAGS = -pthread -Wall -Wundef -Wunused-parameter -Wno-ctor-dtor-privacy -Woverloaded-virtual -Wno-deprecated-declarations -O2 -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gtk-3.0/unix-print -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gio-unix-2.0 -I/usr/include/atk-1.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -fPIC -DPIC  
WX_LDFLAGS = -pthread  
SAMPLES_CXXFLAGS =  -fPIC -DPIC

### Variables: ###

DESTDIR = 
WX_RELEASE = 3.1
LIBDIRNAME = lib
APP_CXXFLAGS = $(WX_CPPFLAGS) -D__WX$(TOOLKIT)__ \
	$(WX_CXXFLAGS) $(SAMPLES_CXXFLAGS) $(CPPFLAGS) $(CXXFLAGS)
APP_OBJECTS = app.o campanel.o

### Conditionally set variables: ###
CXXC = $(CXX)

EXTRALIBS_FOR_GUI = $(EXTRALIBS_GUI)
__WXLIB_AUI_p = -lwx_gtk3_aui-$(WX_RELEASE)
__WXLIB_HTML_p = -lwx_gtk3_html-$(WX_RELEASE)
__WXLIB_CORE_p = -lwx_gtk3_core-$(WX_RELEASE)
__WXLIB_XML_p = -lwx_base$(WXBASEPORT)_xml-$(WX_RELEASE)
__WXLIB_BASE_p = -lwx_base$(WXBASEPORT)-$(WX_RELEASE)

ifneq "$(findstring debug, $(MAKECMDGOALS))" ""
	CXXFLAGS  = -std=c++11 -O0 -DDEBUG -g
	CONFIG 		= debug
else
	CXXFLAGS  = -std=c++11 -O3 -DNDEBUG 
	CONFIG 		= release
endif

APP_CXXFLAGS += $(CXXFLAGS)

BUILD_STEP = PRE_BUILD all POST_BUILD
ifneq "$(findstring clean, $(MAKECMDGOALS))" ""
debug		: ; @true
else
build		: | $(BUILD_STEP)
debug		: build
endif

### Targets: ###
all: app

clean: 
	rm -rf ./.deps ./.pch
	rm -f ./*.o
	rm -f app

app: $(APP_OBJECTS)
	$(CXX) -o $@ $(APP_OBJECTS) -L$(LIBDIRNAME) $(OPENCVLIB)  $(LDFLAGS)  $(WX_LDFLAGS) $(__WXLIB_AUI_p)  $(__WXLIB_HTML_p) $(__WXLIB_CORE_p)  $(__WXLIB_XML_p) $(EXTRALIBS_XML) $(__WXLIB_BASE_p)  $(__WXLIB_MONO_p) $(__LIB_SCINTILLA_IF_MONO_p) $(__LIB_TIFF_p) $(__LIB_JPEG_p) $(__LIB_PNG_p)  $(EXTRALIBS_FOR_GUI) $(__LIB_ZLIB_p) $(__LIB_REGEX_p) $(__LIB_EXPAT_p) $(EXTRALIBS) $(LIBS)

%.o: %.cpp
	$(CXXC) -c -o $@ $(APP_CXXFLAGS) $(OPENCVLIB)  $<


# Include dependency info, if present:
-include ./.deps/*.d

.PHONY: all clean debug


PRE_BUILD:
			@echo ========================================
			@echo CONFIG: $(CONFIG)
			@echo CXXFLAGS: $(CXXFLAGS)
			@echo ========================================

POST_BUILD:
			@echo finished....